INSERT INTO MEMBER (FULLNAME, EMAIL, PASSWORD) VALUES ('Fredrik Hagman', 'fredrik.hagman@hm.com', '123');
INSERT INTO MEMBER (FULLNAME, EMAIL, PASSWORD) VALUES ('Åsa Lindkvist', 'asa.lindkvist@hm.com', '123');
INSERT INTO MEMBER (FULLNAME, EMAIL, PASSWORD) VALUES ('Yusri Shakir', 'yusri.shakir@hm.com', '123');
INSERT INTO MEMBER (FULLNAME, EMAIL, PASSWORD) VALUES ('Robert Stigsson', 'robert.stigsson@hm.com', '123');

INSERT INTO CATEGORY (CATEGORYNAME) VALUES('lunch');
INSERT INTO CATEGORY (CATEGORYNAME) VALUES('exercise');
INSERT INTO CATEGORY (CATEGORYNAME) VALUES('run');
INSERT INTO CATEGORY (CATEGORYNAME) VALUES('fika');
INSERT INTO CATEGORY (CATEGORYNAME) VALUES('meet');


<<<<<<< HEAD
INSERT INTO ACTIVITY (CATEGORYID, ACTIVITYNAME, MAXMEMBERS, ACTIVITYDATE, ACTIVITYTIME, LOCATION) VALUES
(3, 'Springa på lunchen', 8, '2020-12-24', '12:00', 'utanför ingången');

INSERT INTO ACTIVITY (CATEGORYID, ACTIVITYNAME, MAXMEMBERS, ACTIVITYDATE,ACTIVITYTIME , LOCATION) VALUES
(2, 'Promenera på lunchen', 4, '2020-12-22', '11:00', 'Möts utanför m28a');

INSERT INTO ACTIVITY (CATEGORYID, ACTIVITYNAME, MAXMEMBERS, ACTIVITYDATE,ACTIVITYTIME , LOCATION) VALUES
(1, 'Äta på Nida', 4, '2020-12-23', '12:00', 'Möts vid spärrarna');

INSERT INTO ACTIVITY (CATEGORYID, ACTIVITYNAME, MAXMEMBERS, ACTIVITYDATE,ACTIVITYTIME , LOCATION) VALUES
(1, 'Äta ute: Indiskt', 4, '2020-12-19', '11:00', 'Möts vid kajen');
=======
INSERT INTO ACTIVITY (CATEGORYID, ACTIVITYNAME, MAXMEMBERS, ACTIVITYDATE, LOCATION) VALUES
(1, 'Springa på lunchen', 8, {ts '2020-12-24 12:00:00.0'}, 'Möts utanför stora ingången');

INSERT INTO ACTIVITY (CATEGORYID, ACTIVITYNAME, MAXMEMBERS, ACTIVITYDATE , LOCATION) VALUES
(1, 'Promenera på lunchen', 4, {ts '2020-12-16 11:00:00.0'}, 'Möts utanför m28a');

INSERT INTO ACTIVITY (CATEGORYID, ACTIVITYNAME, MAXMEMBERS, ACTIVITYDATE , LOCATION) VALUES
(2, 'Äta på Nida', 4, {ts '2020-12-20 12:00:00.0'}, 'Möts vid spärrarna');

INSERT INTO ACTIVITY (CATEGORYID, ACTIVITYNAME, MAXMEMBERS, ACTIVITYDATE , LOCATION) VALUES
(2, 'Äta ute: Indiskt', 4, {ts '2020-12-15 11:00:00.0'}, 'Möts vid kajen');
>>>>>>> 62aa2462b8f93c6910a7738f9f276672fd900b92


INSERT INTO MEMBERACTIVITY (MEMBERID, ACTIVITYID, ISOWNER) VALUES ((SELECT MEMBERID FROM MEMBER WHERE FULLNAME ='Fredrik Hagman'), (SELECT ACTIVITYID FROM ACTIVITY WHERE ACTIVITYID = '1'), '1');
INSERT INTO MEMBERACTIVITY (MEMBERID, ACTIVITYID, ISOWNER) VALUES ((SELECT MEMBERID FROM MEMBER WHERE FULLNAME ='Åsa Lindkvist'), (SELECT ACTIVITYID FROM ACTIVITY WHERE ACTIVITYID = '2'), '1');
INSERT INTO MEMBERACTIVITY (MEMBERID, ACTIVITYID, ISOWNER) VALUES ((SELECT MEMBERID FROM MEMBER WHERE FULLNAME ='Yusri Shakir'), (SELECT ACTIVITYID FROM ACTIVITY WHERE ACTIVITYID = '3'), '1');
INSERT INTO MEMBERACTIVITY (MEMBERID, ACTIVITYID, ISOWNER) VALUES ((SELECT MEMBERID FROM MEMBER WHERE FULLNAME ='Robert Stigsson'), (SELECT ACTIVITYID FROM ACTIVITY WHERE ACTIVITYID = '4'), '1');